repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
        files: ^fastapi-application/.*\.py$
        exclude: ^alembic/
      - id: ruff
        name: ruff
        entry: ruff check
        language: system
        types: [ python ]
        files: ^fastapi-application/.*\.py$
        exclude: ^alembic/
