version: "3.9"

services:

  pg:
    image: postgres:latest
    container_name: postgres_db_queue_api
    environment:

      POSTGRES_DB: queue_api
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "queue_api"]
      interval: 15s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 15s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      pg:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis_queue_api
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 5s
      retries: 3

  mongo:
    image: mongo:6.0
    container_name: mongodb_queue_api
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    restart: always
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 15s
      timeout: 5s
      retries: 5

  migrations:
    build: .
    container_name: migrations_service
    env_file:
      - .env.docker.template
      - .env.docker
    command: alembic upgrade head
    healthcheck:
      test: ["CMD", "exit", "0"]
      disable: true
    depends_on:
      pg:
        condition: service_healthy
    restart: "no"
    networks:
      - backend

  app:
    build: .
    container_name: fastapi_app
    env_file:
      - .env.docker.template
      - .env.docker
    ports:
      - "50000:50000"
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migrations:
        condition: service_started
    restart: unless-stopped
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:50000/api_v1/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3

  worker:
    build: .
    container_name: celery_worker
    env_file:
      - .env.docker.template
      - .env.docker
    environment:
      BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      DATABASE_URL: postgresql://user:password@pg:5432/queue_api
      REDIS_URL: redis://redis:6379/0
    command: celery -A tasks.celery_app worker --loglevel=INFO --concurrency=4 --queues logs,errors
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend
    healthcheck:
      test: ["CMD", "celery", "-A", "tasks.celery_app", "status"]
      interval: 15s
      timeout: 5s
      retries: 3

volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local
  mongo-data:
    driver: local
  mongo-config:
    driver: local

networks:
  backend:
    driver: bridge